import Cards from "./modules/Cards.js";
import Clientslugu from "./modules/Clientslugu.js";
import Menu from "./modules/Menu.js";
import Number from "./modules/Numbers.js";
import Sample from "./modules/Sample.js";
import Serviceha from "./modules/Serviceha.js";
import Teammembers from "./modules/Teammembers.js";
Clientslugu();
Teammembers();
Sample();
Number();
Serviceha();
Cards();
Menu();
